/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import javax.swing.JOptionPane;
/**
 *
 * @author amosp
 */
public class currency extends javax.swing.JFrame {

    /**
     * Creates new form currency
     */
    public currency() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtamount = new javax.swing.JTextField();
        txtfrom = new javax.swing.JComboBox<>();
        txtto = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("Enter the Amount ");

        jLabel2.setText("From");

        jLabel3.setText("To");

        txtamount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtamountActionPerformed(evt);
            }
        });

        txtfrom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "USD", "Euro", "SriLankan Rupees", "Indian Rupees", "British Pound", "Japanese Yen", "Canadian Dollar", "Swiss Franc", "Chinese Renmimbi", "Hong Kong Dollar", "New Zealand Dollar", "Australian Dollar" }));

        txtto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SriLankan Rupees", "Indian Rupees", "Euro", "British Pound", "Japanese Yen", "Canadian Dollar", "Swiss Franc", "Chinese Renmimbi", "Hong Kong Dollar", "New Zealand Dollar", "Australian Dollar", "USD" }));

        jButton1.setText("Convert");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(133, 321, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtamount)
                            .addComponent(txtfrom, 0, 165, Short.MAX_VALUE)
                            .addComponent(txtto, 0, 0, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtamount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtfrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(txtto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        Double total;
        Double amount = Double.parseDouble(txtamount.getText());
        
        //From USD to Any--------------------------------------------------------------------------------
        if(txtfrom.getSelectedItem().toString().equals("USD"))
        { 
            if(txtto.getSelectedItem().toString().equals( "SriLankan Rupees")){
                total = amount * 186.60;
                JOptionPane.showMessageDialog(this, "Your Amount will be " + total.toString());
            }
            else if(txtto.getSelectedItem().toString().equals("Indian Rupees")){
                total = amount * 73.73;
                JOptionPane.showMessageDialog(this, "Your Amount will be " + total.toString());
            }
            else if(txtto.getSelectedItem().toString().equals("Euro")){
                total = amount * .81;
                JOptionPane.showMessageDialog(this, "Your Amount will be " + total.toString());
            }
            else if(txtto.getSelectedItem().toString().equals("British Pound")){
                total = amount * .75;
                JOptionPane.showMessageDialog(this, "Your Amount will be " + total.toString());
            }
            else if(txtto.getSelectedItem().toString().equals("Japanese Yen")){
                total = amount * 103.46;
                JOptionPane.showMessageDialog(this, "Your Amount will be " + total.toString());
            }
            else if(txtto.getSelectedItem().toString().equals("Canadian Dollar")){
                total = amount * 1.29;
                JOptionPane.showMessageDialog(this, "Your Amount will be " + total.toString());
            }
            else if(txtto.getSelectedItem().toString().equals("Swiss Franc")){
                total = amount * .89;
                JOptionPane.showMessageDialog(this, "Your Amount will be " + total.toString());
            }
            else if(txtto.getSelectedItem().toString().equals("Chinese Renmimbi")){
                total = amount * 6.55;
                JOptionPane.showMessageDialog(this, "Your Amount will be " + total.toString());
            }
            else if(txtto.getSelectedItem().toString().equals("Hong Kong Dollar")){
                total = amount * 7.75;
                JOptionPane.showMessageDialog(this, "Your Amount will be " + total.toString());
            }
            else if(txtto.getSelectedItem().toString().equals("Australian Dollar")){
                total = amount * 1.32;
                JOptionPane.showMessageDialog(this, "Your Amount will be " + total.toString());
            }
        }
        
        //From Euro to Any-------------------------------------------------------------------------------
        if(txtfrom.getSelectedItem().toString().equals("Euro"))
        { 
            if(txtto.getSelectedItem().toString().equals( "SriLankan Rupees")){
                total = amount * 227.75;
                JOptionPane.showMessageDialog(this, "Your Amount will be " + total.toString());
            }
            else if(txtto.getSelectedItem().toString().equals("Indian Rupees")){
                total = amount * 89.99;
                JOptionPane.showMessageDialog(this, "Your Amount will be " + total.toString());
            }
            else if(txtto.getSelectedItem().toString().equals("USD")){
                total = amount * 1.22;
                JOptionPane.showMessageDialog(this, "Your Amount will be " + total.toString());
            }
            else if(txtto.getSelectedItem().toString().equals("British Pound")){
                total = amount * .91;
                JOptionPane.showMessageDialog(this, "Your Amount will be " + total.toString());
            }
            else if(txtto.getSelectedItem().toString().equals("Japanese Yen")){
                total = amount * 126.28;
                JOptionPane.showMessageDialog(this, "Your Amount will be " + total.toString());
            }
            else if(txtto.getSelectedItem().toString().equals("Canadian Dollar")){
                total = amount * 1.57;
                JOptionPane.showMessageDialog(this, "Your Amount will be " + total.toString());
            }
            else if(txtto.getSelectedItem().toString().equals("Swiss Franc")){
                total = amount * 1.08;
                JOptionPane.showMessageDialog(this, "Your Amount will be " + total.toString());
            }
            else if(txtto.getSelectedItem().toString().equals("Chinese Renmimbi")){
                total = amount * 7.99;
                JOptionPane.showMessageDialog(this, "Your Amount will be " + total.toString());
            }
            else if(txtto.getSelectedItem().toString().equals("Hong Kong Dollar")){
                total = amount * 9.46;
                JOptionPane.showMessageDialog(this, "Your Amount will be " + total.toString());
            }
            else if(txtto.getSelectedItem().toString().equals("Australian Dollar")){
                total = amount * 1.61;
                JOptionPane.showMessageDialog(this, "Your Amount will be " + total.toString());
            }
        }
        
        //From SriLankan Rupee to Any--------------------------------------------------------------------
        if(txtfrom.getSelectedItem().toString().equals("SriLankan Rupees"))
        { 
            if(txtto.getSelectedItem().toString().equals( "Euro")){
                total = amount * .004;
                JOptionPane.showMessageDialog(this, "Your Amount will be " + total.toString());
            }
            else if(txtto.getSelectedItem().toString().equals("Indian Rupees")){
                total = amount * .39;
                JOptionPane.showMessageDialog(this, "Your Amount will be " + total.toString());
            }
            else if(txtto.getSelectedItem().toString().equals("USD")){
                total = amount * .005;
                JOptionPane.showMessageDialog(this, "Your Amount will be " + total.toString());
            }
            else if(txtto.getSelectedItem().toString().equals("British Pound")){
                total = amount * .004;
                JOptionPane.showMessageDialog(this, "Your Amount will be " + total.toString());
            }
            else if(txtto.getSelectedItem().toString().equals("Japanese Yen")){
                total = amount * .55;
                JOptionPane.showMessageDialog(this, "Your Amount will be " + total.toString());
            }
            else if(txtto.getSelectedItem().toString().equals("Canadian Dollar")){
                total = amount * .0069;
                JOptionPane.showMessageDialog(this, "Your Amount will be " + total.toString());
            }
            else if(txtto.getSelectedItem().toString().equals("Swiss Franc")){
                total = amount * .0049;
                JOptionPane.showMessageDialog(this, "Your Amount will be " + total.toString());
            }
            else if(txtto.getSelectedItem().toString().equals("Chinese Renmimbi")){
                total = amount * .035;
                JOptionPane.showMessageDialog(this, "Your Amount will be " + total.toString());
            }
            else if(txtto.getSelectedItem().toString().equals("Hong Kong Dollar")){
                total = amount * .041;
                JOptionPane.showMessageDialog(this, "Your Amount will be " + total.toString());
            }
            else if(txtto.getSelectedItem().toString().equals("Australian Dollar")){
                total = amount * .0069;
                JOptionPane.showMessageDialog(this, "Your Amount will be " + total.toString());
            }
        }
        
        //From Indian Rupee to Any-----------------------------------------------------------------------
        if(txtfrom.getSelectedItem().toString().equals("Indian Rupees"))
        { 
            if(txtto.getSelectedItem().toString().equals( "Euro")){
                total = amount * .011;
                JOptionPane.showMessageDialog(this, "Your Amount will be " + total.toString());
            }
            else if(txtto.getSelectedItem().toString().equals("SriLankan Rupees")){
                total = amount * 2.53;
                JOptionPane.showMessageDialog(this, "Your Amount will be " + total.toString());
            }
            else if(txtto.getSelectedItem().toString().equals("USD")){
                total = amount * .0135;
                JOptionPane.showMessageDialog(this, "Your Amount will be " + total.toString());
            }
            else if(txtto.getSelectedItem().toString().equals("British Pound")){
                total = amount * .010;
                JOptionPane.showMessageDialog(this, "Your Amount will be " + total.toString());
            }
            else if(txtto.getSelectedItem().toString().equals("Japanese Yen")){
                total = amount * 1.40;
                JOptionPane.showMessageDialog(this, "Your Amount will be " + total.toString());
            }
            else if(txtto.getSelectedItem().toString().equals("Canadian Dollar")){
                total = amount * .0174;
                JOptionPane.showMessageDialog(this, "Your Amount will be " + total.toString());
            }
            else if(txtto.getSelectedItem().toString().equals("Swiss Franc")){
                total = amount * .012;
                JOptionPane.showMessageDialog(this, "Your Amount will be " + total.toString());
            }
            else if(txtto.getSelectedItem().toString().equals("Chinese Renmimbi")){
                total = amount * .0887;
                JOptionPane.showMessageDialog(this, "Your Amount will be " + total.toString());
            }
            else if(txtto.getSelectedItem().toString().equals("Hong Kong Dollar")){
                total = amount * .10497;
                JOptionPane.showMessageDialog(this, "Your Amount will be " + total.toString());
            }
            else if(txtto.getSelectedItem().toString().equals("Australian Dollar")){
                total = amount * .01791;
                JOptionPane.showMessageDialog(this, "Your Amount will be " + total.toString());
            }
        }
        
        //From British Pound to Any-----------------------------------------------------------------------
        if(txtfrom.getSelectedItem().toString().equals("British Pound"))
        { 
            if(txtto.getSelectedItem().toString().equals( "Euro")){
                total = amount * 1.097;
                JOptionPane.showMessageDialog(this, "Your Amount will be " + total.toString());
            }
            else if(txtto.getSelectedItem().toString().equals("SriLankan Rupees")){
                total = amount * 249.95;
                JOptionPane.showMessageDialog(this, "Your Amount will be " + total.toString());
            }
            else if(txtto.getSelectedItem().toString().equals("USD")){
                total = amount * 1.339;
                JOptionPane.showMessageDialog(this, "Your Amount will be " + total.toString());
            }
            else if(txtto.getSelectedItem().toString().equals("Indian Rupees")){
                total = amount * 98.87 ;
                JOptionPane.showMessageDialog(this, "Your Amount will be " + total.toString());
            }
            else if(txtto.getSelectedItem().toString().equals("Japanese Yen")){
                total = amount * 138.59;
                JOptionPane.showMessageDialog(this, "Your Amount will be " + total.toString());
            }
            else if(txtto.getSelectedItem().toString().equals("Canadian Dollar")){
                total = amount * 1.7256;
                JOptionPane.showMessageDialog(this, "Your Amount will be " + total.toString());
            }
            else if(txtto.getSelectedItem().toString().equals("Swiss Franc")){
                total = amount * 1.188;
                JOptionPane.showMessageDialog(this, "Your Amount will be " + total.toString());
            }
            else if(txtto.getSelectedItem().toString().equals("Chinese Renmimbi")){
                total = amount * 8.764;
                JOptionPane.showMessageDialog(this, "Your Amount will be " + total.toString());
            }
            else if(txtto.getSelectedItem().toString().equals("Hong Kong Dollar")){
                total = amount * 10.38;
                JOptionPane.showMessageDialog(this, "Your Amount will be " + total.toString());
            }
            else if(txtto.getSelectedItem().toString().equals("Australian Dollar")){
                total = amount * 1.77429;
                JOptionPane.showMessageDialog(this, "Your Amount will be " + total.toString());
            }
        }
        
        //From Japanese Yen to Any-----------------------------------------------------------------------
        if(txtfrom.getSelectedItem().toString().equals("Japanese Yen"))
        { 
            if(txtto.getSelectedItem().toString().equals( "Euro")){
                total = amount * .00792;
                JOptionPane.showMessageDialog(this, "Your Amount will be " + total.toString());
            }
            else if(txtto.getSelectedItem().toString().equals("SriLankan Rupees")){
                total = amount * 1.80;
                JOptionPane.showMessageDialog(this, "Your Amount will be " + total.toString());
            }
            else if(txtto.getSelectedItem().toString().equals("USD")){
                total = amount * .00966;
                JOptionPane.showMessageDialog(this, "Your Amount will be " + total.toString());
            }
            else if(txtto.getSelectedItem().toString().equals("Indian Rupees")){
                total = amount * .71 ;
                JOptionPane.showMessageDialog(this, "Your Amount will be " + total.toString());
            }
            else if(txtto.getSelectedItem().toString().equals("British Pound")){
                total = amount * .00721;
                JOptionPane.showMessageDialog(this, "Your Amount will be " + total.toString());
            }
            else if(txtto.getSelectedItem().toString().equals("Canadian Dollar")){
                total = amount * .01245;
                JOptionPane.showMessageDialog(this, "Your Amount will be " + total.toString());
            }
            else if(txtto.getSelectedItem().toString().equals("Swiss Franc")){
                total = amount * .00857;
                JOptionPane.showMessageDialog(this, "Your Amount will be " + total.toString());
            }
            else if(txtto.getSelectedItem().toString().equals("Chinese Renmimbi")){
                total = amount * .06323;
                JOptionPane.showMessageDialog(this, "Your Amount will be " + total.toString());
            }
            else if(txtto.getSelectedItem().toString().equals("Hong Kong Dollar")){
                total = amount * .07490;
                JOptionPane.showMessageDialog(this, "Your Amount will be " + total.toString());
            }
            else if(txtto.getSelectedItem().toString().equals("Australian Dollar")){
                total = amount * .0128;
                JOptionPane.showMessageDialog(this, "Your Amount will be " + total.toString());
            }
        }
        
        //From Canadian Dollar to Any-----------------------------------------------------------------------
        if(txtfrom.getSelectedItem().toString().equals("Canadian Dollar"))
        { 
            if(txtto.getSelectedItem().toString().equals( "Euro")){
                total = amount * .63567;
                JOptionPane.showMessageDialog(this, "Your Amount will be " + total.toString());
            }
            else if(txtto.getSelectedItem().toString().equals("SriLankan Rupees")){
                total = amount * 144.827;
                JOptionPane.showMessageDialog(this, "Your Amount will be " + total.toString());
            }
            else if(txtto.getSelectedItem().toString().equals("USD")){
                total = amount * .7759;
                JOptionPane.showMessageDialog(this, "Your Amount will be " + total.toString());
            }
            else if(txtto.getSelectedItem().toString().equals("Indian Rupees")){
                total = amount * 57.29 ;
                JOptionPane.showMessageDialog(this, "Your Amount will be " + total.toString());
            }
            else if(txtto.getSelectedItem().toString().equals("Japanese Yen")){
                total = amount * 80.30;
                JOptionPane.showMessageDialog(this, "Your Amount will be " + total.toString());
            }
            else if(txtto.getSelectedItem().toString().equals("British Pound")){
                total = amount * .57933;
                JOptionPane.showMessageDialog(this, "Your Amount will be " + total.toString());
            }
            else if(txtto.getSelectedItem().toString().equals("Swiss Franc")){
                total = amount * .68845;
                JOptionPane.showMessageDialog(this, "Your Amount will be " + total.toString());
            }
            else if(txtto.getSelectedItem().toString().equals("Chinese Renmimbi")){
                total = amount * 5.07816;
                JOptionPane.showMessageDialog(this, "Your Amount will be " + total.toString());
            }
            else if(txtto.getSelectedItem().toString().equals("Hong Kong Dollar")){
                total = amount * 6.01;
                JOptionPane.showMessageDialog(this, "Your Amount will be " + total.toString());
            }
            else if(txtto.getSelectedItem().toString().equals("Australian Dollar")){
                total = amount * 1.02806;
                JOptionPane.showMessageDialog(this, "Your Amount will be " + total.toString());
            }
        }
        
        //From Swiss Franc to Any-----------------------------------------------------------------------
        if(txtfrom.getSelectedItem().toString().equals("Swiss Franc"))
        { 
            if(txtto.getSelectedItem().toString().equals( "Euro")){
                total = amount * .92318;
                JOptionPane.showMessageDialog(this, "Your Amount will be " + total.toString());
            }
            else if(txtto.getSelectedItem().toString().equals("SriLankan Rupees")){
                total = amount * 210.318;
                JOptionPane.showMessageDialog(this, "Your Amount will be " + total.toString());
            }
            else if(txtto.getSelectedItem().toString().equals("USD")){
                total = amount * 1.126;
                JOptionPane.showMessageDialog(this, "Your Amount will be " + total.toString());
            }
            else if(txtto.getSelectedItem().toString().equals("Indian Rupees")){
                total = amount * 83.1995 ;
                JOptionPane.showMessageDialog(this, "Your Amount will be " + total.toString());
            }
            else if(txtto.getSelectedItem().toString().equals("Japanese Yen")){
                total = amount * 116.62;
                JOptionPane.showMessageDialog(this, "Your Amount will be " + total.toString());
            }
            else if(txtto.getSelectedItem().toString().equals("Canadian Dollar")){
                total = amount * 1.45198;
                JOptionPane.showMessageDialog(this, "Your Amount will be " + total.toString());
            }
            else if(txtto.getSelectedItem().toString().equals("British Pound")){
                total = amount * .841;
                JOptionPane.showMessageDialog(this, "Your Amount will be " + total.toString());
            }
            else if(txtto.getSelectedItem().toString().equals("Chinese Renmimbi")){
                total = amount * 7.37452;
                JOptionPane.showMessageDialog(this, "Your Amount will be " + total.toString());
            }
            else if(txtto.getSelectedItem().toString().equals("Hong Kong Dollar")){
                total = amount * 8.7359;
                JOptionPane.showMessageDialog(this, "Your Amount will be " + total.toString());
            }
            else if(txtto.getSelectedItem().toString().equals("Australian Dollar")){
                total = amount * 1.49296;
                JOptionPane.showMessageDialog(this, "Your Amount will be " + total.toString());
            }
        }
        
        //From Chinese Renmimbi to Any-----------------------------------------------------------------------
        if(txtfrom.getSelectedItem().toString().equals("Chinese Renmimbi"))
        { 
            if(txtto.getSelectedItem().toString().equals( "Euro")){
                total = amount * .12514;
                JOptionPane.showMessageDialog(this, "Your Amount will be " + total.toString());
            }
            else if(txtto.getSelectedItem().toString().equals("SriLankan Rupees")){
                total = amount * 28.51;
                JOptionPane.showMessageDialog(this, "Your Amount will be " + total.toString());
            }
            else if(txtto.getSelectedItem().toString().equals("USD")){
                total = amount * .15275;
                JOptionPane.showMessageDialog(this, "Your Amount will be " + total.toString());
            }
            else if(txtto.getSelectedItem().toString().equals("Indian Rupees")){
                total = amount * 11.2783 ;
                JOptionPane.showMessageDialog(this, "Your Amount will be " + total.toString());
            }
            else if(txtto.getSelectedItem().toString().equals("Japanese Yen")){
                total = amount * 15.81;
                JOptionPane.showMessageDialog(this, "Your Amount will be " + total.toString());
            }
            else if(txtto.getSelectedItem().toString().equals("Canadian Dollar")){
                total = amount * .19683;
                JOptionPane.showMessageDialog(this, "Your Amount will be " + total.toString());
            }
            else if(txtto.getSelectedItem().toString().equals("Swiss Franc")){
                total = amount * .13553;
                JOptionPane.showMessageDialog(this, "Your Amount will be " + total.toString());
            }
            else if(txtto.getSelectedItem().toString().equals("British Pound")){
                total = amount * .11405;
                JOptionPane.showMessageDialog(this, "Your Amount will be " + total.toString());
            }
            else if(txtto.getSelectedItem().toString().equals("Hong Kong Dollar")){
                total = amount * 1.18422;
                JOptionPane.showMessageDialog(this, "Your Amount will be " + total.toString());
            }
            else if(txtto.getSelectedItem().toString().equals("Australian Dollar")){
                total = amount * .20238;
                JOptionPane.showMessageDialog(this, "Your Amount will be " + total.toString());
            }
        }
        
        //From Hong Kong Dollar to Any-----------------------------------------------------------------------
        if(txtfrom.getSelectedItem().toString().equals("Hong Kong Dollar"))
        { 
            if(txtto.getSelectedItem().toString().equals( "Euro")){
                total = amount * .10566;
                JOptionPane.showMessageDialog(this, "Your Amount will be " + total.toString());
            }
            else if(txtto.getSelectedItem().toString().equals("SriLankan Rupees")){
                total = amount * 24.0738;
                JOptionPane.showMessageDialog(this, "Your Amount will be " + total.toString());
            }
            else if(txtto.getSelectedItem().toString().equals("USD")){
                total = amount * .1289;
                JOptionPane.showMessageDialog(this, "Your Amount will be " + total.toString());
            }
            else if(txtto.getSelectedItem().toString().equals("Indian Rupees")){
                total = amount * 9.52334 ;
                JOptionPane.showMessageDialog(this, "Your Amount will be " + total.toString());
            }
            else if(txtto.getSelectedItem().toString().equals("Japanese Yen")){
                total = amount * 13.35;
                JOptionPane.showMessageDialog(this, "Your Amount will be " + total.toString());
            }
            else if(txtto.getSelectedItem().toString().equals("Canadian Dollar")){
                total = amount * .16620;
                JOptionPane.showMessageDialog(this, "Your Amount will be " + total.toString());
            }
            else if(txtto.getSelectedItem().toString().equals("Swiss Franc")){
                total = amount * .11444;
                JOptionPane.showMessageDialog(this, "Your Amount will be " + total.toString());
            }
            else if(txtto.getSelectedItem().toString().equals("Chinese Renmimbi")){
                total = amount * .84412;
                JOptionPane.showMessageDialog(this, "Your Amount will be " + total.toString());
            }
            else if(txtto.getSelectedItem().toString().equals("British Pound")){
                total = amount * .09630;
                JOptionPane.showMessageDialog(this, "Your Amount will be " + total.toString());
            }
            else if(txtto.getSelectedItem().toString().equals("Australian Dollar")){
                total = amount * .17089;
                JOptionPane.showMessageDialog(this, "Your Amount will be " + total.toString());
            }
        }
        
        //From Australian Dollar to Any-----------------------------------------------------------------------
        if(txtfrom.getSelectedItem().toString().equals("Australian Dollar"))
        { 
            if(txtto.getSelectedItem().toString().equals( "Euro")){
                total = amount * .61823;
                JOptionPane.showMessageDialog(this, "Your Amount will be " + total.toString());
            }
            else if(txtto.getSelectedItem().toString().equals("SriLankan Rupees")){
                total = amount * 140.842;
                JOptionPane.showMessageDialog(this, "Your Amount will be " + total.toString());
            }
            else if(txtto.getSelectedItem().toString().equals("USD")){
                total = amount * .7546;
                JOptionPane.showMessageDialog(this, "Your Amount will be " + total.toString());
            }
            else if(txtto.getSelectedItem().toString().equals("Indian Rupees")){
                total = amount * 55.7155 ;
                JOptionPane.showMessageDialog(this, "Your Amount will be " + total.toString());
            }
            else if(txtto.getSelectedItem().toString().equals("Japanese Yen")){
                total = amount * 78.10;
                JOptionPane.showMessageDialog(this, "Your Amount will be " + total.toString());
            }
            else if(txtto.getSelectedItem().toString().equals("Canadian Dollar")){
                total = amount * .9723;
                JOptionPane.showMessageDialog(this, "Your Amount will be " + total.toString());
            }
            else if(txtto.getSelectedItem().toString().equals("Swiss Franc")){
                total = amount * .66951;
                JOptionPane.showMessageDialog(this, "Your Amount will be " + total.toString());
            }
            else if(txtto.getSelectedItem().toString().equals("Chinese Renmimbi")){
                total = amount * 4.93844;
                JOptionPane.showMessageDialog(this, "Your Amount will be " + total.toString());
            }
            else if(txtto.getSelectedItem().toString().equals("Hong Kong Dollar")){
                total = amount * 5.85012;
                JOptionPane.showMessageDialog(this, "Your Amount will be " + total.toString());
            }
            else if(txtto.getSelectedItem().toString().equals("British Pound")){
                total = amount * .56339;
                JOptionPane.showMessageDialog(this, "Your Amount will be " + total.toString());
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtamountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtamountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtamountActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(currency.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(currency.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(currency.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(currency.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new currency().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtamount;
    private javax.swing.JComboBox<String> txtfrom;
    private javax.swing.JComboBox<String> txtto;
    // End of variables declaration//GEN-END:variables
}
